### ISSUE TITLE
numpy deprecation warning

### ISSUE THREAD

**Issue by dstansby** [wtbarnes/fiasco#120]
Should probably fix this:

```python
/Users/dstansby/github/fiasco/fiasco/util/tools.py:175: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  nots = np.array(list(map(splrep_szero, x, y)))
```

**Comment by dstansby** [comment]
FYI I'm still getting this warning:
```python
/Users/dstansby/github/fiasco/fiasco/util/tools.py:155: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.asarray(x)
```

**Comment by wtbarnes** [comment]
Ah I think I understand. The warning is popping up in a different place than last time.

The reason this isn't popping up in the tests is because we are not testing the Fe XII ion. The array in question is only ragged (and thus only triggers this warning) for some ions. The fits over the scaled collision strengths may or may not all be the same length and this varies per ion.

The solution to suppressing this is to add some more sanitization to the inputs to `burgess_tully_descale`.
