### ISSUE TITLE
Hydrogen- and helium-like atoms only for Z > 6 and 10?

### ISSUE THREAD

**Issue by jwreep** [wtbarnes/fiasco#251]
The definition of hydrogen-like requires `Z > 6`:
```return (self.atomic_number - self.charge_state == 1) and (self.atomic_number >= 6)```
and helium-like `Z > 10`:
```return (self.atomic_number - self.charge_state == 2) and (self.atomic_number >= 10)```

Why is this?  Is He II not hydrogen-like?  Or is there some logic or functionality that only applies to elements with higher atomic numbers?

**Comment by wtbarnes** [comment]
That is a good question...I think I created these properties in order to use them in the ionization cross-section calculation here: https://github.com/wtbarnes/fiasco/blob/282b819f5a9b257db93d1d484fa63ada2cb0c610/fiasco/ions.py#L943 and here: https://github.com/wtbarnes/fiasco/blob/282b819f5a9b257db93d1d484fa63ada2cb0c610/fiasco/ions.py#L975. I was following the logic both from the Fontes cross-section paper as well as what is in the `ioniz_cross.pro` routine: https://sohoftp.nascom.nasa.gov/solarsoft/packages/chianti/idl/ionrec/ioniz_cross.pro

The conditions on $Z$ are likely just specific to that calculation so that condition should be dropped from these properties. I'm actually still a bit confused by the $Z\ge6$ condition. In the Fontes cross-section paper, it explicitly states that these cross-section calculations are for $10\le Z\le 92$ so the $Z\ge10$ condition makes sense, but I don't understand the $Z\ge6$ condition.

**Comment by jwreep** [comment]
Perhaps it would be worth dropping this in the definitions, and putting the requirements on atomic number into the cross-section calculation directly?  I could handle that, if so.
