### ISSUE TITLE
Units/Suggestions.

### ISSUE THREAD

**Issue by ktbug** [wtbarnes/fiasco#31]
Hi

Just out of curiosity,
Should density for radiative loss be able to handle kg/m^3 not just m^3?

Second suggestion---- include a tutorial to have just installation with an anaconda virtual environment. Using Python 3.6 with other Pythons were causing issues with my Ubuntu.

Thanks

**Comment by wtbarnes** [comment]
Because of the way the expression for the emissivity is derived (See Eqs. 1 and 2 of [Dere et al. (1997)](https://aas.aanda.org/articles/aas/abs/1997/13/ds1260/ds1260.html)), I'm not exactly sure how the mass density (as opposed to the number density) would work as an input. Do you have a particular use case in mind where you need to input the mass density?

In the installation docs, I've linked to [a page in the SunPy docs](http://docs.sunpy.org/en/stable/guide/installation/index.html#installing-scientific-python-and-sunpy) where they go into a bit more detail about setting up Anaconda. Probably a link about conda environments/virtual environments would be helpful.

**Comment by wtbarnes** [comment]
I think the first point is out of the scope of the package.

Regarding the second point, the link to the SunPy docs provides extensive instructions on installing Python with Anaconda.
