### ISSUE TITLE
Add feedback on calculation progress

### ISSUE THREAD

**Issue by dstansby** [wtbarnes/fiasco#87]
Some calculations (e.g. the contribution function for Fe XIII, which has 42667 transitions) can take a long time, so it would be nice to give the user some sort of feedback on the progress of the calculation.

In my head this is in the form of a progress bar, perhaps something like https://github.com/tqdm/tqdm that works in both a terminal and a jupyter notebook. It should probably also be an option, maybe via the fiasco configuration file (to save a bunch of kwargs floating round to turn on or off progress reporting)

**Comment by wtbarnes** [comment]
I responded to this in my mind, but apparently never actually typed it out 😄 

I completely understand the want for this. It is a bit annoying that a lot of these calculations take a long time without any feedback as to how much compute time is left. However, at least in the case of the contribution (really the level population calculation as this is where all the time is spent), I'm opposed to this for a few reasons:

1. My preference is to make as little noise as possible, by default at least. Especially if this tool is being folded into a larger simulation or analysis pipeline, it's annoying having things printing to the screen. 
2. I don't actually think a progress bar would offer you anything in the case of the contribution function calculation because the main bottle neck is not an explicit iteration. This could work in the case where you have multiple densities I guess, but sometimes even a single density can take a while and the blocking computation there is the solution of the N-by-N matrix of transition rates. That's just a numpy call so its progress can't really be reported.

This could be useful when calculating multi-ion quantities in a collection (e.g. radiative loss curves, spectra).

However, my preferred solution to this would be to implement a proper logger and use it consistently throughout the package, similar to what we've done in sunpy. That way, we have a consistent way of giving feedback to users and the noisiness can be adjusted as appropriate. This doesn't really solve the issue brought up in point two, but I don't really see a way around that.

**Comment by wtbarnes** [comment]
I'm going to close this for the reasons I've listed above. I think the right way to proceed with this is to implement a logger.
