### ISSUE TITLE
Don't silently return None when a value can't be computed

### ISSUE THREAD

**Issue by dstansby** [wtbarnes/fiasco#93]
Currently the `needs_dataset` silently (eek!) returns `None` if a dataset isn't needed. This confused me for a while, and I think it should at least warn. Looking through the places where this decorator is used, I think it might be reasonable to error too if a dataset isn't present.

e.g. if I don't have the files needed to calculate `ion.transitions`, calling `ion.transitions` should probably raise an error. I think #89 is a subset of this issue for specific case of abundances.

**Comment by wtbarnes** [comment]
I'm very glad this issue was raised. This was a decision I made early on and one that I am becoming increasingly uneasy with. #89 is a great example of where this is causing problems. 

I guess I'll try to explain my reasoning for doing this and maybe this will lead to a possible solution. So the `needs_dataset` decorator will force a function to return `None` if the ion does not have the information needed to do that particular calculation. This is an issue in CHIANTI because not every ion has the same number of data files associated with it. For example, Fe I has no `.elvlc` file associated with it in the database. Thus, we cannot do any calculation which requires information about the energy levels of that ion. Alternatively, it may be that an abundance set may not have entries for every element and so calculations requiring the abundance won't be possible for the given ion and abundance set (this is what is happening in #89).

In my initial conception of all this, I didn't think of this as an exception. To me, raising an exception implies something unexpected has happened. However, this outcome is expected. No information is available in the database and so the function returns `None`. Also, when computing multi-ion quantities such as spectra or radiative loss curves, it's a bit weird to have to deal with an exception. 

However, now that I'm typing all of this out, `None` here is really an exception of its own, albeit a non-explicit one. As you point out, this is certainly not ideal and is confusing. It also can mean where an exception gets raised for some of these functions is somewhat non-deterministic as `None` may be able to be passed through some parts of the stack and not others and it's hard to know where exactly the "stopping depth" is. The worst outcome, of course, is getting an answer back when you don't expect to get one.

**Comment by wtbarnes** [comment]
A proposed solution: create a `MissingDatasetException` class and raise this when a dataset is not present. This will mean a deep dive into all the places where I've handled the possible occurrence of a None, but I don't think that will be too bad. 

We may want something a bit more forgiving in the future, but I now think it is best to be as explicit as possible now.

**Comment by dstansby** [comment]
Sounds good! I might try and bump the test coverage of everything before attempting this change...

**Comment by wtbarnes** [comment]
Yeah this project is in desperate need of better test coverage. Thanks!

**Comment by wtbarnes** [comment]
Oof now realizing I have to actually wrap my head around the logic of this decorator I wrote two years ago 😭
